infinitered/bluepotion

- lib/project/ruby_motion_query/stylers/rmq_image_view_styler.rb
- lib/project/ruby_motion_query/stylers/rmq_linear_layout_styler.rb
added a useful alias.   src for image, since that's what is used in xml.
Also, rendered styler to use POTION nomenclature.
> a few styler updates

- app/screens/home_screen.rb
- app/stylesheets/example_table_screen_stylehseet.rb
- app/stylesheets/home_screen_stylesheet.rb
- lib/project/pro_motion/activities/pm_navigation_activity.rb
Otherwise it crashes after 15 opens in one activity.
> Fixed fragment stack for PMNavigationActivity

- lib/project/ext/object.rb
> Better output for array contents

- lib/project/potion.rb
- lib/project/pro_motion/adapters/pm_adapter_module.rb
- lib/project/pro_motion/adapters/pm_base_adapter.rb
- lib/project/pro_motion/adapters/pm_cursor_adapter.rb
- lib/project/pro_motion/fragments/pm_list_screen.rb
- lib/project/ruby_motion_query/rmq/base.rb
This is a bare-bones implementation of `PMListScreen`. The API works something like this:
```ruby
class NormalScreen < PMListScreen
title "Normal with an array"
def table_data
[
{ title: "item 1", action: :something, arguments: { some: "args" }, cell_class: Potion::TextView },
{ title: "item 2", action: :something, arguments: { some: "args" }, cell_class: Potion::TextView },
{ title: "item 3", action: :something, arguments: { some: "args" }, cell_class: Potion::TextView },
{ title: "item 4", action: :something, arguments: { some: "args" }, cell_class: Potion::TextView },
{ title: "item 5", action: :something, arguments: { some: "args" }, cell_class: Potion::TextView },
]
end
def something(arguments, position)
cell = adapter.item(position)
end
end
class CursorScreen < PMListScreen
title …
```
> [WIP] Initial work on PMListScreen

- Gemfile.lock
- lib/project/pro_motion/activities/pm_activity.rb
- lib/project/pro_motion/fragments/pm_list_screen.rb
- lib/project/pro_motion/fragments/pm_screen.rb
- lib/project/pro_motion/fragments/pm_screen_module.rb
You can now do this:
```ruby
class MyScreen < PMScreen
action_bar true, back: true
end
```
When you open/close a screen, it'll automatically show or hide the action bar and the back button. Defaults to true/true.
@twerth
> Much better action bar and back button handling

- lib/project/alert_dialog/alert_dialog.rb
- lib/project/pro_motion/pm_application.rb
We can do alerts like RedAlert style.
```ruby
app.alert(title: "Hey There", message: "Want a sandwich?") do |choice|
case choice
when "OK"
mp "Here's your sandwich"
when "Cancel"
mp "Fine!"
end
end
```
> Add app.alert - Like RedAlert

- lib/project/pro_motion/fragments/pm_list_screen.rb
- lib/project/pro_motion/fragments/pm_screen.rb
- lib/project/pro_motion/fragments/pm_screen_module.rb
You can now do this:
```ruby
class MyScreen < PMScreen
action_bar true, back: true, icon: true,
custom_icon: "mycustomicon", custom_back: "mycustomback"
```
> Added icon, custom_icon, custom_back options to action_bar

- lib/project/pro_motion/pm_application.rb
> added ability to access app.name

- app/screens/example_table_screen.rb
- lib/project/pro_motion/adapters/pm_base_adapter.rb
- lib/project/pro_motion/fragments/pm_list_screen.rb
> Pm list screen

- lib/project/delayed_execution.rb
- lib/project/potion.rb
- lib/project/pro_motion/pm_application.rb
You can now do:
```ruby
app.after(10) do
p "This will run after 10 seconds."
end
```
> Add app.after method for running a block after a delay

- lib/project/ruby_motion_query/rmq/events.rb
Little typo there preventing on(:change) magic.
> Fix for text changed event.

- lib/project/ruby_motion_query/rmq/styles.rb
Precious precious `RMQ#reapply_styles`.
> Support for reapply_styles.

- lib/project/ruby_motion_query/stylers/rmq_text_view_styler.rb
Set-only support for text view stylers.  Needed this for disabling a button.
> Enabled support for text view stylers.

- lib/project/ruby_motion_query/rmq_resource.rb
```ruby
RMQResource.string :step_1_title
app.r.string :cut_a_hole_in_a_box_label
```
> Fetch a string resource value.

- README.md
* documentation covering some issues I hit when trying to setup for the first time
> Some small readme updates

- lib/project/pro_motion/activities/pm_activity.rb
Fixes #54. Merge if @skellock says it's okay.
> Added back button detection

- lib/project/pro_motion/fragments/pm_list_screen.rb
- lib/project/ruby_motion_query/rmq/base.rb
cursor list wasn't playing nicely anymore.
> Fix cursor list

- lib/project/pro_motion/fragments/pm_list_screen.rb
- lib/project/pro_motion/pm_application.rb
```ruby
app.launch(sms: '5045558008')
app.launch(tel: '5045558008')
app.launch(web: 'http://giphy.com')
app.launch(email: 'your@mom.com')
app.launch(email: 'your@mom.com', subject: "Hey Chica", message: "Howdy")
app.launch(chooser: 'I hope you have a nice day!')
```
takes care of request in issue #66
> Launcher feature

- README.md
> Add more instructions to the readme

- bin/bluepotion
Noticed the discussion in #84, and the previous fix in redpotion so threw this up quick to solve #84
> Updates to clone template from https

- app/screens/example_partial_list_xml_screen.rb
- app/screens/home_screen.rb
- resources/layout/dialog_list_view.xml
- resources/layout/embedded_listview.xml
Look @markrickert I'm doing a PR instead of merging myself into master.   Don't get used to this.
> Listview in dialog

- bluepotion.gemspec
We wouldn't want to lose our lovely Java hacks in the generated gem file...
> Include .java files in the gemspec

- lib/project/pro_motion/activities/pm_navigation_activity.rb
solves #101 thanks to @jamonholmgren
> this should work to pass options to the fragments through the call to #open.

- lib/project/alert_dialog/alert_dialog.rb
I needed a numeric input in an app I was writing so I thought I'd have a go at implementing that. Let me know what you think.
> Input Type Support

- lib/project/pro_motion/activities/pm_activity.rb
- lib/project/pro_motion/fragments/pm_screen_module.rb
built ability to disable (native android) back button for some screens into bluepotion
> ability to use "back_button false" to disable the android back button for that screen

- lib/project/ruby_motion_query/rmq/event_wrappers/rmq_checked_change.rb
- lib/project/ruby_motion_query/rmq/event_wrappers/rmq_focus_listener.rb
- lib/project/ruby_motion_query/rmq/event_wrappers/rmq_select_change.rb
- lib/project/ruby_motion_query/rmq/events.rb
Add few events
- `.on(:change, &block)`   
- for `Checkbox` and `RadioButton` -> `block.call(true|false)`  
- for `RadioGroup` -> `block.call(checked_id)`  
- for `Spinner` -> `block.call(selected_id)`  
- `.on(:focus, &block)`   -> `block.call(true|false) -> # boolean is has_focus`
> new events

- lib/project/alert_dialog/alert_dialog.rb
- Add an option `cancelable`
- Call `prepare_view` to allow extended classes to build their view
- Call `on_dialog_created` when the dialog is created to allow fine tuning of the `Dialog`
> AlertDialog

- lib/project/ext/time.rb
- lib/project/ruby_motion_query/rmq/event_wrappers/rmq_date_listener.rb
When I PR #111, I forgot to add Time#from_string, which is needed by `PotionDateTimePicker` (damn broken specs on Android :'( )
> Forgot to add the Time#from_string
