Gemfile.lock
lib/project/pro_motion/pm_screen.rb

Each id in XML is a string, when RMQ wanted a resource.   I fixed the `setup_xml_widgets` to work with that conversion.
Ideally, RMQ find could try to look into the XML rather than returning 0 results.  Let's discuss.

xml widgets need resource id's for RMQ wrap

---

lib/project/pro_motion/pm_screen_module.rb

We'll need to do some `on_return` goodness, probably. And since we're a fragment, closing the whole activity might not be desirable. But it does work.

Added very basic close method to screens

---

lib/project/pro_motion/pm_activity.rb
lib/project/pro_motion/pm_screen.rb
lib/project/pro_motion/pm_screen_module.rb
lib/project/pro_motion/pm_single_fragment_activity.rb

Added `on_attach`, `on_create`, `on_create_view`, `on_activity_created` (same as `on_load`), `on_start`, `on_resume`, `on_pause`, `on_stop`, `on_destroy_view`, `on_destroy`, `on_detach`.
Also added a preliminary version of `add_action_bar_button`. It's pretty rough, needs work, but does create a button.

Added lifecycle methods, set_action_bar_button

---

lib/project/pro_motion/pm_screen_module.rb

I added aliases so older code doesn't break, but I like this better. I think I'll be introducing the `nav_bar` one into ProMotion iOS. Related: https://github.com/clearsightstudio/ProMotion/issues/631#issuecomment-105079694

Renamed uses_xml and uses_action_bar to layout and nav_bar

---

lib/project/ruby_motion_query/rmq/event_wrappers/rmq_click.rb
lib/project/ruby_motion_query/rmq/event_wrappers/rmq_seek_change.rb
lib/project/ruby_motion_query/rmq/event_wrappers/rmq_text_change.rb
lib/project/ruby_motion_query/rmq/events.rb

This commit adds the ability to click on listitems, as well as changing text and the seek bar.
I've restructured the way we build RMQ Events to be more scalable for all wrappers to come.

Add more events

---

lib/project/pro_motion/pm_activity.rb
lib/project/pro_motion/pm_screen_module.rb
lib/project/pro_motion/pm_single_fragment_activity.rb

You can now do:
```ruby
def on_create_menu(menu)
add_action_bar_button title: "Test 1", show: :if_room, action: :some_method
add_action_bar_button title: "Test 2", show: :if_room, action: :some_other_method
end
```
... and it'll work like ProMotion iOS.
Also added icon:
```ruby
def on_create_menu(menu)
add_action_bar_button icon: :my_icon, show: :if_room, action: :some_method
end
```

Added actions for action bar buttons

---

lib/project/pro_motion/fragments/pm_screen.rb

In ProMotion-iOS, `load_view` expects you to assign the view:
```ruby
def load_view
self.view = UIView.new
end
```
This brings ProMotion-Android in line with that.
```ruby
def load_view
self.view = Potion::FrameLayout.new(self.activity)
end
```
It's backwards-compatible, in that if you do *not* assign the view but rather return it, PM-android will do the right thing and assign it for you.
```ruby
def load_view
Potion::FrameLayout.new(self.activity) # assigned to self.view anyway
end
```

Change load_view semantics to match ProMotion-ios

---

Gemfile
Gemfile.lock
app/screens/home_screen.rb
app/stylesheets/application_stylesheet.rb
app/stylesheets/home_screen_stylesheet.rb
lib/project/pro_motion/pm_application.rb

This adds `app.async` as a wrapper for the [motion-async](https://github.com/darinwilson/motion-async) gem, and adds some sample usage to the BluePotion app home screen.
Resolves #17

Integrate motion-async for asychronous tasks

---

app/screens/example_table_screen.rb
app/screens/example_xml_screen.rb
app/screens/home_screen.rb
app/stylesheets/home_screen_stylesheet.rb
lib/project/pro_motion/activities/pm_activity.rb
lib/project/pro_motion/activities/pm_navigation_activity.rb
lib/project/pro_motion/fragments/pm_list_screen.rb
lib/project/pro_motion/fragments/pm_screen.rb
lib/project/pro_motion/fragments/pm_screen_module.rb
resources/layout/example_xml_screen.xml

This gets the example XML layout screen working, which required a change to the way fragments are pulled on screen. We're now using `replace` rather than `add`, which fixes the problem of old fragments appearing underneath the current fragment. 
This change also works better with the hardware back button, so we could get rid of our hand-rolled implementation of `onBackPressed`

Add an example XML screen, and modify fragment loading behavior

---

lib/project/ruby_motion_query/rmq/selectors.rb

In this case, the culprit was `match` and it didn't happen on all API versions.

Fix another conflict with a simiarly-named Java method

---

lib/project/pro_motion/fragments/pm_screen_module.rb

Needed the ability to show the keyboard because simply setting `focus` doesn't seem to trigger the keyboard to appear.
```ruby
rmq.screen.show_keyboard
```

Show the keyboard.

---

lib/project/pro_motion/fragments/pm_list_screen.rb

Before triggering `adapter.notifyDataSetChanged`, we need to feed it the changed data from our `PMListScreen`.

Fix for stale adapter data during update_table_data

---

lib/project/pro_motion/adapters/pm_base_adapter.rb

Cells that are powered by just a layout file don't need to handle `#update`.  Just removing the warning cry from bp.

Remove warning when cells aren't :update powered.

---

lib/project/ruby_motion_query/stylers/rmq_text_view_styler.rb

The `finalize` of the text styler was overriding the styling applied in our layout xml file.
I'll follow up with @darinwilson to see if we can eliminate dodging lazy style applying as a best practice.  It may not be easy as some Android need to be set in pairs (layout params) or sub objects (typeface).
Perhaps we could start introducing hash-based property if we're required.  Like good ol'  `:frame`.
I encountered some of these things in `motion-mastr` as the NSAttributedString customization involved sub-objects (NSParagraphStyle).   But then again, `motion-mastr`'s interface is entirely hash-based.
Now I'm rambling.  Now's the time! The time is now!

Only set the font when it actually changes.

---

lib/project/pro_motion/adapters/pm_base_adapter.rb

Wasn't able to `find(:cell_label)` after cells were created.  Just needed to tag 'em up.

Tag all inflated rows spawned by the base adapter.

---

lib/project/alert_dialog/alert_dialog.rb

The kind of crash that gives you no info.    
On Android 4 it dumps the activity.  You get Dalvik'd.
On Android 5 it spews misinformation at you.
I actually ended up running it on the device to figure out the real problem.  
So strange.

Guard against a crash when app.dialog isn't given style: :input.

---

lib/project/pro_motion/adapters/pm_base_adapter.rb
lib/project/pro_motion/adapters/pm_cursor_adapter.rb

Two things.
1. Recently the interface for `item` changed to `item_data` in base adapter.  This commit brings that up to par.
2.  Also, turns out, base adapter already has the implementation of creating/reusing/prepping views, so I nuked all that inside here as it was slightly out of date anyway.
For science!

Fix Cursor Adapter Issues

---

lib/project/pro_motion/fragments/pm_screen_module.rb

This mode allows the keyboard to sit ontop of the controls.  UI Controls won't reflow.

Keyboard pan mode to prevent ui control squishing.

---

lib/project/potion_dialog/potion_dialog.rb

I needed to get the `Android::App::Dialog`, but it was trapped inside the `PotionDialog`.
I'm finding this interface a bit confusing to be honest.  Maybe it's the name?  Maybe I expected `PotionDialog` to be an `Android::App::Dialog`.
I think end game would be have this dialog be an `PMScreen`, but I'm having a hard time wrapping my head around how to make that happen as `PMScreen`s are `Fragment`s.
This commit unblocks me though!  I can `findViewById` and `rmq.wrap` to accomplish what i need short-term.

Expose the Potion::Dialog from the PotionDialog.

---

Rakefile
app/screens/example_partial_list_xml_screen.rb
app/screens/example_table_screen.rb
lib/project/pro_motion/fragments/pm_list_screen.rb
lib/project/pro_motion/fragments/pm_screen.rb
lib/project/pro_motion/fragments/refreshable_list.rb
lib/project/ruby_motion_query/rmq/event_wrappers/ptr_handler.rb
resources/layout/embedded_listview.xml

The code is a lot like iOS.   Just add `refreshable` to the class, and use `on_refresh` and `stop_refreshing`.   This requires the ultra pull to refresh gradle
```ruby
dependency 'in.srain.cube:ultra-ptr:1.0.10'
```
Wrap your listview in the XML tag to identify what is Pull to Refresh
```xml
<in.srain.cube.views.ptr.PtrClassicFrameLayout
android:id="@+id/store_house_ptr_frame"
xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
android:layout_width="match_parent"
android:layout_height="match_parent">
<ListView
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:id="@+id/list_view"
android:layout_gravity="center_horizontal" />
</in.srain.cube.views.ptr.PtrClassicFrameLayout>
```
I'd love to remove this, so listviews are automatically wrapped, but that's a …

Basic Refreshable

---

lib/project/pro_motion/fragments/pm_list_screen.rb

In case you have 2 ListViews on 1 Screen, here's another way to specify which one is driven by the adapter.  Override `find_list_view` and provide your own.

Allows finding of the list view to be overridden.

---

lib/project/ext/time.rb

Ensures that when we `Time.iso8601` a date, the timezone offset is taken into account.

What happens in UTC, stays in UTC.

---

lib/project/pro_motion/adapters/pm_base_adapter.rb
lib/project/pro_motion/fragments/pm_list_screen.rb

An adapter can start requesting data from it's list screen prior to blue potion setting the proper PMScreen on `find.screen`.
This tells the adapter explicitly who the parent screen is, so we're not firing off update methods against the "last" screen.
Another option might be to start the adapter in a paused state so the data doesn't flow until `find.screen` is the right one.

Adapter screen timing fix

---

Rakefile

To run bluepotion specs with "rake spec:device", it need to build ARM binary instead of "x86"

build ARM binary to run spec on device with "rake spec:device"

---

lib/project/ruby_motion_query/rmq_resource.rb

Use `app.r.text(:foo)` when your `foo` string resource is actually a `Spannable`.  `<string name='foo'><b>o</b>m<b>g</b></string>`!!

Fetch text (CharSequence) from resources.

---

lib/project/volley_wrap/request.rb

Let's say I want to request a page with an array of ids. 
The params should be something like `url?id[]=1&id[]=2` or `url?id[0]=1&id[1]=2`
This PR allows the use of `Array` in params and `prepare_params` to fit this array notation
The use will be 
```ruby
app.net.post(SomeUrl, { ids: [1, 2] }) 
```

Allow array as param

---

lib/project/progress_hud/progress_hud.rb

This PR adds the possibility to set a `max` attribute on a new `ProgressHUD` and then use `hud.increment` to set the progress
The following video came from this example
```ruby
find(R::Id::Progress).on(:tap) do |_|
@hud = ProgressHUD.new('Loading', style: :horizontal, max: 100)
@hud.show
app.async do
(0..100).each do |_|
@hud.increment
sleep 0.2
end
end.on(:completion) do |_|
@hud.dismiss
end
end
```
You can also use `increment(some_value)`
[![BP ProgressHUD ](http://img.youtube.com/vi/dS24XN1LhL8/0.jpg)](http://www.youtube.com/watch?v=dS24XN1LhL8)
This PR also complete #16

Add a progressbar to ProgressHUD

---

lib/project/date_dialog/potion_date_time_picker.rb
lib/project/ruby_motion_query/rmq/event_wrappers/rmq_date_listener.rb
lib/project/ruby_motion_query/rmq/event_wrappers/rmq_time_listener.rb
lib/project/ruby_motion_query/rmq/events.rb

This PR adds DatePicker and TimePicker
```ruby
PotionDateTimePicker.new do |time|
mp time.to_s
end
```
```ruby
PotionDateTimePicker.new(type: :time) do |hour, minute|
mp "#{hour}:#{minute}"
end
```
There are few options like `:time`, `:hour`, ...

PotionDateTimePicker

---

lib/project/pro_motion/activities/pm_activity.rb

This PR allows adding a `on_back_pressed` on a `Screen`. 
This method will be called (if exists ofc) by `PMActivity#onBackPressed`.

Call on_back_pressed

---

lib/project/pro_motion/support/pm_hash_bundle.rb

Newer versions of RubyMotion return short strings (e.g. `String`, `Symbol`) for class names in Java/Android. I've updated the type checking in `PMHashBundle` to add the shorter class names. Previously these shorter names were falling through the `when` conditions to cause "invalid type" exceptions.

Fix PMHashBundle type checking for recent RubyMotion versions
